defer_request_response:
  pattern: /{id}
  defaults: { _controller: ZeroemDeferredRequestBundle:Api:deferredResponse }
  requirements:
    _method: GET

defer_request_monitor:
  pattern: /{id}/monitor
  defaults: { _controller: ZeroemDeferredRequestBundle:Api:deferredRequestStatus }
  requirements:
    _method: GET