services:
  defer_request_defer_annotation_driver:
    class: Zeroem\DeferredRequestBundle\Annotation\Driver\DeferDriver
    tags: [{name: kernel.event_listener, event: kernel.controller, method: onKernelController}]
    arguments:
      - @annotation_reader
      - @event_dispatcher
      - @defer_request_persister
      - @defer_response_builder

  defer_request_queue_annotation_driver:
    class: Zeroem\DeferredRequestBundle\Annotation\Driver\QueueDriver
    tags: [{name: kernel.event_listener, event:deferred-request.deferred, method: onDefer}]
    arguments:
      - @annotation_reader
      - @defer_request_queue_manager

  defer_response_builder:
    class: Zeroem\DeferredRequestBundle\Response\ResponseBuilder
    arguments: [@router]

  defer_request_persister:
    class: Zeroem\DeferredRequestBundle\Persistence\Entity
    arguments: [@doctrine.orm.default_entity_manager]